# Generated by Django 3.1.1 on 2020-09-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kib_app', '0004_auto_20200909_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image_thumb_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
