# Generated by Django 3.1.1 on 2020-09-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kib_app', '0005_auto_20200909_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='preparation',
        ),
    ]
