# Generated by Django 3.1.1 on 2020-09-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kib_app', '0006_remove_drink_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
