# Generated by Django 3.1.1 on 2020-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kib_app', '0007_auto_20200909_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image_thumb_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
